default: ec2_yum_linux
ec2_yum_linux:
    cloud: ec2
    distro: redhat
    provisioner: yum
    volume: linux
    blockdevice: linux
    finalizer: tagging_ebs
ec2_apt_linux:
    cloud: ec2
    distro: debian
    provisioner: apt
    volume: linux
    blockdevice: linux
    finalizer: tagging_ebs
ec2_aptitude_linux:
    cloud: ec2
    distro: debian
    provisioner: aptitude
    volume: linux
    blockdevice: linux
    finalizer: tagging_ebs
